/*
 * Copyright (C) 2013 DobinRutishauser@broken.ch
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package gui.mainBot;

import gui.viewMessage.ViewMessageLinkManager;
import java.util.LinkedList;
import model.SentinelHttpMessage;
import model.SentinelHttpMessageAtk;
import model.SentinelHttpMessageOrig;
import util.SettingsManager;
 
/**
 *
 * @author unreal
 */
public class PanelBotUi extends javax.swing.JPanel {

    private ViewMessageLinkManager linkManager;
    
    /**
     * Creates new form PanelBotUi
     */
    public PanelBotUi() {
        linkManager = new ViewMessageLinkManager();
        initComponents();
    }
    
    public PanelBotUi(SentinelHttpMessageOrig iHttpRequestResponse) {
        this();
                
        SettingsManager.restoreSplitLocation(jSplitPane1, this);
        panelLeftUi.setMessage(iHttpRequestResponse);
        panelRightUi.setMessage(iHttpRequestResponse);
        
        panelLeftUi.setPanelParent(this);
        panelRightUi.setPanelParent(this);
    }
    
    // Called when attacking from leftpanel
    public void addAttackMessage(SentinelHttpMessageAtk httpMessage) {
        panelRightUi.addHttpMessage(httpMessage);
    }
    
    public ViewMessageLinkManager getLinkManager() {
        return linkManager;
    }
   
    
    public SentinelHttpMessage getOrigMessage() {
        SentinelHttpMessage orig = panelLeftUi.getOrigHttpMessage();
        return orig;
    }
    
    public LinkedList<SentinelHttpMessageAtk> getAttackMessages() {
        return panelRightUi.getAttackMessage();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        panelRightTop = new javax.swing.JPanel();
        panelRightUi = new gui.botRight.PanelRightUi();
        jPanel1 = new javax.swing.JPanel();
        panelLeftTop = new javax.swing.JPanel();
        panelLeftUi = new gui.botLeft.PanelLeftUi();

        jPanel2.setLayout(new java.awt.BorderLayout());

        panelRightTop.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelRightTop.setLayout(new java.awt.BorderLayout());
        panelRightTop.add(panelRightUi, java.awt.BorderLayout.CENTER);

        jPanel2.add(panelRightTop, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(jPanel2);

        jPanel1.setLayout(new java.awt.BorderLayout());

        panelLeftTop.setLayout(new java.awt.BorderLayout());
        panelLeftTop.add(panelLeftUi, java.awt.BorderLayout.CENTER);

        jPanel1.add(panelLeftTop, java.awt.BorderLayout.CENTER);

        jSplitPane1.setLeftComponent(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1223, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel panelLeftTop;
    private gui.botLeft.PanelLeftUi panelLeftUi;
    private javax.swing.JPanel panelRightTop;
    private gui.botRight.PanelRightUi panelRightUi;
    // End of variables declaration//GEN-END:variables

    public void storeUiPrefs() {
        SettingsManager.storeSplitLocation(jSplitPane1, this);
        
        panelLeftUi.storeUiPrefs();
        panelRightUi.storeUiPrefs();
    }
}
